// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB5LKpiykuvb3ityjHbyIax84X03UmLzEk',
    appId: '1:758162152618:web:9d181df27cd253ed4c04d3',
    messagingSenderId: '758162152618',
    projectId: 'siddhanth2022-d98fa',
    authDomain: 'siddhanth2022-d98fa.firebaseapp.com',
    storageBucket: 'siddhanth2022-d98fa.appspot.com',
    measurementId: 'G-BCF61FN6SC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDNaaqVVQIAhAZSDeP4t03mH5_BdKUyRUg',
    appId: '1:758162152618:android:234bcebdb611c7b94c04d3',
    messagingSenderId: '758162152618',
    projectId: 'siddhanth2022-d98fa',
    storageBucket: 'siddhanth2022-d98fa.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAct4Vho_ccHH5FipzhPriF8KSsycTJ63U',
    appId: '1:758162152618:ios:17a707e9e8865dd64c04d3',
    messagingSenderId: '758162152618',
    projectId: 'siddhanth2022-d98fa',
    storageBucket: 'siddhanth2022-d98fa.appspot.com',
    iosClientId: '758162152618-65o41ercs7s9na5a6s37eq3slr313qvb.apps.googleusercontent.com',
    iosBundleId: 'com.svs.siddhanth.siddhanth',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAct4Vho_ccHH5FipzhPriF8KSsycTJ63U',
    appId: '1:758162152618:ios:17a707e9e8865dd64c04d3',
    messagingSenderId: '758162152618',
    projectId: 'siddhanth2022-d98fa',
    storageBucket: 'siddhanth2022-d98fa.appspot.com',
    iosClientId: '758162152618-65o41ercs7s9na5a6s37eq3slr313qvb.apps.googleusercontent.com',
    iosBundleId: 'com.svs.siddhanth.siddhanth',
  );
}
